apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: token-inventory

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Uncomment to add common labels
# commonLabels:
#   app.kubernetes.io/name: token-inventory
#   app.kubernetes.io/instance: production
